name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 1 * * 5' # Every Friday at 01:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false # so we can use our own token

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Sheppard-Lab/GOLD-GWAS.git
          git fetch upstream

      - name: Merge upstream/main into forked main
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes to fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main
